services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "project-php"
    volumes:
      - ./src:/var/www/html
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    ports:
      - "9000:9000"

  # --- MariaDB 10.5
  db:
    container_name: "project-db"
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: laravel
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      -  ./db:/var/lib/mysql
      -  ./my_conf:/etc/mysql/conf.d

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      -  "8080:80"
    volumes:
      -  ./src:/var/www/html
      -  ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      -  php
      -  db
      -  cloud9

  admin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    links:
      - db
    ports:
      - 8888:80
    volumes:
      - /sessions

  cloud9:
    build:
      context: .
      dockerfile: Dockerfile-cloud9
    command: "node /c9sdk/server.js -w /src --port 8181 --listen 0.0.0.0 --auth :"
    ports:
      - 8181:8181
    volumes:
      - ./src:/src